[[plugins]]
repo = 'Shougo/dein.vim'

# language server protocol
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

# language server settings
[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

# async auto complete
[[plugins]]
repo = 'prabirshrestha/async.vim'

# auto complete plugin
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

# auto complete for lsp
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

# auto complete for ultisnips
[[plugins]]
repo = 'prabirshrestha/asyncomplete-ultisnips.vim'

# snippets
[[plugins]]
repo = 'SirVer/ultisnips'

# snippets collection
[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-ultisnips'

# fuzzy finder
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

# fzf for vim
[[plugins]]
repo = 'junegunn/fzf.vim'

# markdown preview
[[plugins]]
repo = 'skanehira/preview-markdown.vim'

# icons
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# 
[[plugins]]
repo = 'cohama/lexima.vim'

# indentline
[[plugins]]
repo = 'Yggdroot/indentLine'

# auto save
[[plugins]]
repo = 'vim-scripts/vim-auto-save'

# winresizer
[[plugins]]
repo = 'simeji/winresizer'

# start screen
[[plugins]]
repo = 'mhinz/vim-startify'

# filer nerd
[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd =  ['NERDTree', 'NERDTreeVCS', 'NERDTreeFromBookmark', 'NERDTreeToggle', 'NERDTreeFocus', 'NERDTreeMirror', 'NERDTreeClose', 'NERDTreeFind', 'NERDTreeCWD', 'NERDTreeRefreshRoot']
hook_add = '''
	let g:NERDTreeAutoDeleteBuffer = 1
	let g:NERDTreeWinSize = 20
	let g:NERDTreeDirArrows = 1
	let g:NERDTreeHijackNetrw = 0
	let g:NERDTreeMinimalUI = 1
	let g:NERDTreeMouseMode = 1
	let g:NERDTreeQuitOnOpen = 0
	let g:NERDTreeRespectWildIgnore = 1
	let g:NERDTreeShowHidden = 1
	let g:NERDTreeSortHiddenFirst = 1
	let g:NERDTreeIgnore=['\.git$', '\.clean$', '\.swp$', '\.bak$', '\~$', '\.DS_Store']
	let g:NERDTreeMapUpdir=''
'''

# theme
[[plugins]]
repo = 'jacoborus/tender.vim'

# vim help ja
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
		\ 'colorscheme': 'wombat',
		\ 'active': {
			\ 'left': [ ['mode', 'paste'], ['readonly', 'branchName', 'filepath', 'modified'] ]
			\ },
		\ 'component_function':{
			\ 'filepath': 'FilePath',
            \ 'branchName': 'BranchName'
			\ },
        \ 'separator': { 'left': '', 'right': '' },
		\ }
	function! BranchName()
		if exists('*fugitive#head')
			let branch = FugitiveHead()
			return branch !=# '' ? '⭠ '.branch : ''
		endif
		return ''
	endfunction
	function! FilePath()
		if winwidth(0) > 90
			return expand("%:s")
		else
			return expand("%:t")
		endif
	endfunction
	" # hide --INSERT--
	set noshowmode
'''

# quickrun buffer source cod
[[plugins]]
repo = 'thinca/vim-quickrun'

#
# Language
#

# Ruby
[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'alpaca-tc/vim-endwise.git'

# Circleci
[[plugins]]
repo = 'yasuhiroki/circleci.vim'

# Markdown
[[plugins]]
repo = 'moorereason/vim-markdownfmt'

# Yaml
[[plugins]]
repo = 'stephpy/vim-yaml'

[[plugins]]
repo = 'mrk21/yaml-vim'
